name: Quality

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.15"

      - name: Set up Python
        run: uv python install

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: '0.8.15'

      - name: Sync project
        run: uv sync --locked --all-extras --dev

      - name: Lint/format/typecheck
        run: uv run poe check